server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root